version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    environment:
      - MODEL_DIR=/app/models/fine_tuned
      - CONF_THRESH=${CONF_THRESH:-0.5}
      - CLASS_LABELS=${CLASS_LABELS:-}
      - GRAFANA_IFRAME=${GRAFANA_IFRAME:-}    # full URL to your Grafana dashboard
    volumes:
      - ../models:/app/models:ro
      - ../logs:/app/logs
    expose: ["7860","9000"]

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri file:/mlruns --default-artifact-root /mlruns
    volumes: ["../mlruns:/mlruns"]
    expose: ["5000"]

  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    expose: ["9090"]

  grafana:
    image: grafana/grafana:10.4.0
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana-data:/var/lib/grafana
    expose: ["3000"]

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    environment:
      - OAUTH2_PROXY_PROVIDER=${OAUTH_PROVIDER}
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH_COOKIE_SECRET}
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_WHITELIST_DOMAINS=.${ROOT_DOMAIN}
      - OAUTH2_PROXY_REDIRECT_URL=https://${AUTH_HOST}/oauth2/callback
      - OAUTH2_PROXY_UPSTREAMS=file:///dev/null
      - OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS=true
    command:
      - --http-address=0.0.0.0:4180
    expose: ["4180"]

  caddy:
    image: caddy:2.8
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APP_HOST=${APP_HOST}
      - GRAFANA_HOST=${GRAFANA_HOST}
      - MLFLOW_HOST=${MLFLOW_HOST}
      - AUTH_HOST=${AUTH_HOST}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on: [ app, grafana, mlflow, oauth2-proxy, prometheus ]

volumes:
  grafana-data:
  caddy_data:
  caddy_config:
