FROM python:3.10-slim


ENV PIP_NO_CACHE_DIR=1 PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /app


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY . /app/

ENV PORT=7860
EXPOSE 7860

CMD ["python", "app.py"]
